development:
  adapter: postgresql
  encoding: unicode
  database: inaride_development
  pool: 5
  username: narek
  password:
    
test: &test
  adapter: postgresql
  encoding: unicode
  database: inaride_test
  pool: 5
  username: narek
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: inaride_production
  pool: 5
  username: narek
  password:
cucumber:
  <<: *test